### ISSUE TITLE
##Question: Other OAuth2 Providers?

### ISSUE THREAD

**Issue by migeruj** [jebrosen/rocket_oauth2#21]
Hi! Where i can find another examples (i check github and reddit but im looking for facebook and google).

**Comment by jebrosen** [comment]
The [`user_info_hyper_sync_rustls` example](https://github.com/jebrosen/rocket_oauth2/tree/e10c6b45c7935dc4745c7008e363cbd4c5b11cfd/examples/user_info_hyper_sync_rustls) includes both GitHub and Google examples. I don't know of any reddit examples; which one are you referring to?

In any case, the only thing that you should need to change in configuration is to use `facebook` instead of `github` in the `Rocket.toml` file. That will use the login and token exchange URIs for facebook, and the API token returned in the `TokenResponse` should be able to be used with Facebook's API.

**Comment by migeruj** [comment]
My bad, I was looking at the documentation for version 0.0.5. Thanks for example @jebrosen
