### ISSUE TITLE
How to implement refresh token exchange

### ISSUE THREAD

**Issue by hcrohland** [jebrosen/rocket_oauth2#4]
Hi Jeb,

I am wondering how to best implement the refresh token exchange in rocket_oauth2.
As a relative newcomer to rocket I am not sure that I would come up with a good solution.
But here are my thoughts:

Implementing the exchange function is trivial by adding a token type parameter to  Adapter::exchange_token. But how to access it from a request is the question: AFAIU you cannot access a fairing from a request. So we would need to register another object as managed state!?! Does not look very elegant to me.

Do you have any ideas?

Cheers,
Christoph

**Comment by jebrosen** [comment]
In terms of public API I agree that this should only need one new thing: a method or parameter somewhere to exchange a refresh token for a new access token.

The problem is in accessing the configuration for the client credentials, currently locked up behind `OAuth<A, C>` - `C` is not necessarily even nameable and even when it is, it will feel awkward. This might require some fairly large restructuring, but hopefully that restructuring can be done in a way that makes the library easier and/or more flexible to use overall.

**Comment by hcrohland** [comment]
I created PR #7 which adds a function "refresh" to OAuth2<A,C>.

I had to fully implement a struct implementing Callback which adds a lot of boilerplate compared to the naked callback function. Any way around that?

```
pub struct MyCallback;

impl rocket_oauth2::Callback for MyCallback {
    type Responder = MyResult<Redirect>;
    fn callback(&self, request: &Request, token: TokenResponse)
        -> MyResult<Redirect>
    {...}
}

```

**Comment by jebrosen** [comment]
This is reason for the "fairly large restructuring" I was referring to - for both `refresh` and `get_redirect`, the current system where `A, C` is effectively used as a key is inconvenient and also "feels off" whenever I look at it.

I would like to merge #7 (after a review) so that the functionality is available without a breaking change, and after that I'll tackle different API structures.

**Comment by jebrosen** [comment]
This functionality is now available in `master` as `oauth2.refresh(refresh_token)`.

I ended up not being able to get rid of `C` easily, so for now you will still need to use an explicit type as in https://github.com/jebrosen/rocket_oauth2/issues/4#issuecomment-538469520 in order to access methods that take `&self` including `refresh` and `get_redirect`. I did remove `A`, however.
