### ISSUE TITLE
DeserializationError when using Twitch as a provider.

### ISSUE THREAD

**Issue by tyleranton** [jebrosen/rocket_oauth2#9]
When using Twitch as a provider, I get the following error:

`Token exchange failed: Error { kind: DeserializationError(Error("invalid type: sequence, expected a string", line: 1, column: 146)) }.`

Example data returned from Twitch:

```
{
  "access_token": "0123456789abcdefghijABCDEFGHIJ",
  "refresh_token": "eyJfaWQmNzMtNGCJ9%6VFV5LNrZFUj8oU231/3Aj",
  "expires_in": 3600,
  "scope": ["viewing_activity_read"],
  "token_type": "bearer"
}
```

I suspect it may be Twitch returning an array of scopes rather than a space-separated string.

**Comment by jebrosen** [comment]
The relevant section of the RFC is here: https://tools.ietf.org/html/rfc6749#section-3.3

And Twitch's documentation: https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-authorization-code-flow

It is surprising and annoying that their authorization URI correctly expects space-separated `scope`s, but then it goes ahead and sends them back as an array. I think `rocket_oauth2` would need to join arrays, split strings, or accept either a `String` or `Vec<String>` (or perhaps `serde_json::Value`) in order to handle all cases, which is... a frustrating situation.

Do you know if the returned `"scope"` array always has one element per scope, or can the strings themselves also contain multiple scopes separated by spaces?

**Comment by tyleranton** [comment]
I just tested and it returns the scopes as separate elements in the array.

I agree, that's a bit bizarre.

**Comment by jebrosen** [comment]
There are two sides to this issue:

* Parsing. I'm willing to "give in" and accept either a single string, or an array of strings.
* Conveying the scopes. I'm not excited about splitting on spaces or merging spaces into one string.

I've been considering changing `TokenResponse` anyway, and this issue would benefit. Instead of a struct that derives `Deserialize`, I was considering making it a thin wrapper around `serde_json::Value` with accessors such as `as_value() -> &Value`, `access_token() -> &str`, `refresh_token() -> &str`, `scope() -> Option<&str>`. This would allow for accessing any unexpected types via `as_value()` and also be easy to migrate to: most usage would just need to add `()` to convert from a field to method access.

**Comment by jebrosen** [comment]
I've rewritten the `TokenResponse` type in 3867108. The `master` branch should no longer fail with responses such as this, and if necessary you can access the scope yourself with something like `token.as_value().get("scope").and_then(Value::as_array)`.

Would you mind testing this version to confirm?

**Comment by tyleranton** [comment]
I'm receiving the token now with no issues. Thanks for taking the time to make this work!
